// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsFsNFD_eUYXha-NjSvkNirMtM8tRYAeI',
    appId: '1:242098993773:android:01075e59f9a5313ebc5d64',
    messagingSenderId: '242098993773',
    projectId: 'chat-journal-dd397',
    databaseURL: 'https://chat-journal-dd397-default-rtdb.firebaseio.com',
    storageBucket: 'chat-journal-dd397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJXjy35q59YBnvc2Li4NuoHwoBfRWhTE',
    appId: '1:242098993773:ios:8deb2e12a27a9f84bc5d64',
    messagingSenderId: '242098993773',
    projectId: 'chat-journal-dd397',
    databaseURL: 'https://chat-journal-dd397-default-rtdb.firebaseio.com',
    storageBucket: 'chat-journal-dd397.appspot.com',
    iosClientId:
        '242098993773-n83ea2gqekff74f7vr5366nhqj6oqrda.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatJournal',
  );
}
