// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30CdbYy1tuR85bTecb-tSdwrGWBkvo6Y',
    appId: '1:113378297499:web:a93bbfd4a9cb0a2039a83e',
    messagingSenderId: '113378297499',
    projectId: 'journal-db8e0',
    authDomain: 'journal-db8e0.firebaseapp.com',
    databaseURL: 'https://journal-db8e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'journal-db8e0.appspot.com',
    measurementId: 'G-82S619FWC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIOWZchg52ujhadhyP2w04pSiVQKyFPTQ',
    appId: '1:113378297499:android:01dc92a29b38006d39a83e',
    messagingSenderId: '113378297499',
    projectId: 'journal-db8e0',
    databaseURL: 'https://journal-db8e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'journal-db8e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5oR37TNbUIZT79tnsy51QqXrFvu4EZYw',
    appId: '1:113378297499:ios:6982f0df58e950f239a83e',
    messagingSenderId: '113378297499',
    projectId: 'journal-db8e0',
    databaseURL: 'https://journal-db8e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'journal-db8e0.appspot.com',
    iosClientId: '113378297499-3ctuot4c3kmlcn9rm1lm1pmqjh05je31.apps.googleusercontent.com',
    iosBundleId: 'com.simakov.journal.journal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5oR37TNbUIZT79tnsy51QqXrFvu4EZYw',
    appId: '1:113378297499:ios:6982f0df58e950f239a83e',
    messagingSenderId: '113378297499',
    projectId: 'journal-db8e0',
    databaseURL: 'https://journal-db8e0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'journal-db8e0.appspot.com',
    iosClientId: '113378297499-3ctuot4c3kmlcn9rm1lm1pmqjh05je31.apps.googleusercontent.com',
    iosBundleId: 'com.simakov.journal.journal',
  );
}
