// Mocks generated by Mockito 5.3.2 from annotations
// in diary_application/test/utils/mock_chatter_scope.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:diary_application/src/core/domain/models/local/chat/chat_model.dart'
    as _i6;
import 'package:diary_application/src/feature/cubit/chatter/chatter_cubit.dart'
    as _i2;
import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatterState_0 extends _i1.SmartFake implements _i2.ChatterState {
  _FakeChatterState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIList_1<T> extends _i1.SmartFake implements _i3.IList<T> {
  _FakeIList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString([bool? prettyPrint]) => super.toString();
}

class _Fake$ChatterStateCopyWith_2<$Res> extends _i1.SmartFake
    implements _i2.$ChatterStateCopyWith<$Res> {
  _Fake$ChatterStateCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatterCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatterCubit extends _i1.Mock implements _i2.ChatterCubit {
  MockChatterCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeChatterState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ChatterState);
  @override
  _i4.Stream<_i2.ChatterState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.ChatterState>.empty(),
      ) as _i4.Stream<_i2.ChatterState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void emit(_i2.ChatterState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i5.Change<_i2.ChatterState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatterState].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatterState extends _i1.Mock implements _i2.ChatterState {
  MockChatterState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IList<_i6.ChatModel> get chats => (super.noSuchMethod(
        Invocation.getter(#chats),
        returnValue: _FakeIList_1<_i6.ChatModel>(
          this,
          Invocation.getter(#chats),
        ),
      ) as _i3.IList<_i6.ChatModel>);
  @override
  _i2.$ChatterStateCopyWith<_i2.ChatterState> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ChatterStateCopyWith_2<_i2.ChatterState>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$ChatterStateCopyWith<_i2.ChatterState>);
}
