// Mocks generated by Mockito 5.3.2 from annotations
// in diary_application/test/utils/mock_start_screen_scope.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bloc/bloc.dart' as _i4;
import 'package:diary_application/src/feature/cubit/main/start_screen_cubit.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStartScreenState_0 extends _i1.SmartFake
    implements _i2.StartScreenState {
  _FakeStartScreenState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$StartScreenStateCopyWith_1<$Res> extends _i1.SmartFake
    implements _i2.$StartScreenStateCopyWith<$Res> {
  _Fake$StartScreenStateCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StartScreenCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartScreenCubit extends _i1.Mock implements _i2.StartScreenCubit {
  MockStartScreenCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set pageIndex(int? pageIndex) => super.noSuchMethod(
        Invocation.setter(
          #pageIndex,
          pageIndex,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set gNavVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #gNavVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set fabVisible(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #fabVisible,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set hashtag(String? hashtag) => super.noSuchMethod(
        Invocation.setter(
          #hashtag,
          hashtag,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.StartScreenState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeStartScreenState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.StartScreenState);
  @override
  _i3.Stream<_i2.StartScreenState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.StartScreenState>.empty(),
      ) as _i3.Stream<_i2.StartScreenState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void emit(_i2.StartScreenState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i4.Change<_i2.StartScreenState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [StartScreenState].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartScreenState extends _i1.Mock implements _i2.StartScreenState {
  MockStartScreenState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pageIndex => (super.noSuchMethod(
        Invocation.getter(#pageIndex),
        returnValue: 0,
      ) as int);
  @override
  bool get fabVisible => (super.noSuchMethod(
        Invocation.getter(#fabVisible),
        returnValue: false,
      ) as bool);
  @override
  bool get gNavVisible => (super.noSuchMethod(
        Invocation.getter(#gNavVisible),
        returnValue: false,
      ) as bool);
  @override
  String get hashtag => (super.noSuchMethod(
        Invocation.getter(#hashtag),
        returnValue: '',
      ) as String);
  @override
  _i2.$StartScreenStateCopyWith<_i2.StartScreenState> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$StartScreenStateCopyWith_1<_i2.StartScreenState>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$StartScreenStateCopyWith<_i2.StartScreenState>);
}
