// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi6XWDI4EjzdpQgaH7VfH4iraA6HTnGkg',
    appId: '1:1079872076382:web:06f13791d82c97ae10d2cf',
    messagingSenderId: '1079872076382',
    projectId: 'diary-application-757ff',
    authDomain: 'diary-application-757ff.firebaseapp.com',
    storageBucket: 'diary-application-757ff.appspot.com',
    measurementId: 'G-SP12FNKF58',
    databaseURL: 'https://diary-application-757ff-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUtaswkVLJcfi6Pxut7I0A5__QRCEHJs',
    appId: '1:1079872076382:android:f997722c1562f92710d2cf',
    messagingSenderId: '1079872076382',
    projectId: 'diary-application-757ff',
    storageBucket: 'diary-application-757ff.appspot.com',
    databaseURL: 'https://diary-application-757ff-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajkd9ZiFqxlt2gEY812bkMwg2Wb8fkBM',
    appId: '1:1079872076382:ios:cc992cebd90d9cda10d2cf',
    messagingSenderId: '1079872076382',
    projectId: 'diary-application-757ff',
    storageBucket: 'diary-application-757ff.appspot.com',
    iosClientId: '1079872076382-4urbef4clcbfispdvos4jn5lr9l7pkhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApplication',
    databaseURL: 'https://diary-application-757ff-default-rtdb.europe-west1.firebasedatabase.appp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajkd9ZiFqxlt2gEY812bkMwg2Wb8fkBM',
    appId: '1:1079872076382:ios:cc992cebd90d9cda10d2cf',
    messagingSenderId: '1079872076382',
    projectId: 'diary-application-757ff',
    storageBucket: 'diary-application-757ff.appspot.com',
    iosClientId: '1079872076382-4urbef4clcbfispdvos4jn5lr9l7pkhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApplication',
    databaseURL: 'https://diary-application-757ff-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
