// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// DO NOT MODIFY BY HAND
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVjH6UYA_-y55ZyJdpTURGpHpOFOQCAI',
    appId: '1:360518503177:web:529803c57c1a009268a1d8',
    messagingSenderId: '360518503177',
    projectId: 'diary-application-9ac33',
    authDomain: 'diary-application-9ac33.firebaseapp.com',
    databaseURL: 'https://diary-application-9ac33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-application-9ac33.appspot.com',
    measurementId: 'G-4JBQXB05EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARv6ZH7_0yb6EYxVJjxFF9OBsxwMWml1A',
    appId: '1:360518503177:android:4571c2ede78e848b68a1d8',
    messagingSenderId: '360518503177',
    projectId: 'diary-application-9ac33',
    databaseURL: 'https://diary-application-9ac33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-application-9ac33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiknAg72QQjUISpYaYJAMRhcelVxKAYxg',
    appId: '1:360518503177:ios:363764139525388e68a1d8',
    messagingSenderId: '360518503177',
    projectId: 'diary-application-9ac33',
    databaseURL: 'https://diary-application-9ac33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-application-9ac33.appspot.com',
    iosClientId: '360518503177-8hput33bghdmbbcpk8ikgt2k661vv4hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiknAg72QQjUISpYaYJAMRhcelVxKAYxg',
    appId: '1:360518503177:ios:363764139525388e68a1d8',
    messagingSenderId: '360518503177',
    projectId: 'diary-application-9ac33',
    databaseURL: 'https://diary-application-9ac33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diary-application-9ac33.appspot.com',
    iosClientId: '360518503177-8hput33bghdmbbcpk8ikgt2k661vv4hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApplication',
  );
}
