// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9cPlsfDqG3_dda2VJVPNzaaGaNAZg9g',
    appId: '1:959830848159:web:5d0e24f2e3f1d580b928aa',
    messagingSenderId: '959830848159',
    projectId: 'chatjournal-d8c56',
    authDomain: 'chatjournal-d8c56.firebaseapp.com',
    storageBucket: 'chatjournal-d8c56.appspot.com',
    measurementId: 'G-B74XTLERL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_IPxGBXV_ixanITRHfFDc8-fmS2uo78Y',
    appId: '1:959830848159:android:74400d0637ef515cb928aa',
    messagingSenderId: '959830848159',
    projectId: 'chatjournal-d8c56',
    storageBucket: 'chatjournal-d8c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCylzrS5_SawQec6dYkvtl-r27aynQqCX4',
    appId: '1:959830848159:ios:e9f204c2f4823eaab928aa',
    messagingSenderId: '959830848159',
    projectId: 'chatjournal-d8c56',
    storageBucket: 'chatjournal-d8c56.appspot.com',
    iosClientId: '959830848159-rbgkm6t1lve16e24ae53n2f9244fajjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolChatJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCylzrS5_SawQec6dYkvtl-r27aynQqCX4',
    appId: '1:959830848159:ios:e9f204c2f4823eaab928aa',
    messagingSenderId: '959830848159',
    projectId: 'chatjournal-d8c56',
    storageBucket: 'chatjournal-d8c56.appspot.com',
    iosClientId: '959830848159-rbgkm6t1lve16e24ae53n2f9244fajjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolChatJournal',
  );
}
