import 'package:flutter/material.dart';

class ChatIcons {
  static final icons = <IconData>[
    Icons.travel_explore,
    Icons.family_restroom,
    Icons.sports,
    Icons.access_alarm,
    Icons.account_circle,
    Icons.language,
    Icons.favorite,
    Icons.savings,
    Icons.no_drinks,
    Icons.home_work,
    Icons.school,
    Icons.flag,
    Icons.music_note,
    Icons.chair,
    Icons.pets,
    Icons.pool,
    Icons.star,
    Icons.key,
    Icons.child_care,
    Icons.mouse,
    Icons.bed,
    Icons.man,
    Icons.computer,
    Icons.draw,
    Icons.store,
    Icons.card_giftcard,
    Icons.hail,
    Icons.handshake,
    Icons.bus_alert,
    Icons.lock,
    Icons.question_answer,
    Icons.water,
    Icons.car_rental,
  ];
}
